[phases.setup]
nixpacks = ["dotnet-sdk_7"]


[phases.install]
cmd = "dotnet restore --env NIXPACKS_CSHARP_SDK_VERSION=7.0"

[phases.build]
cmd = 'dotnet publish --no-restore -c Release -o {}'

[phases.start]
cmd = './out'