[phases.setup]
nixPkgs=['dotnet-sdk_7','nodejs']

[phases.install]
cmd = "dotnet restore"


[phases.build]
cmds = ['dotnet ef database update', 'dotnet publish --no-restore -c Release -o {}']

[phases.start]
cmd = './out'