[phases.setup]
nixPkgs = ['nodejs', 'dotnet-sdk_7']

[phases.install]
cmd = 'npm ci'

[phases.build]
cmd = 'npm run build'

[phases.start]
cmd = 'dotnet server/bin/Debug/net7.0/publish/todo-dotnet-api.dll'