// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoApi.Models;

#nullable disable

namespace todo_dotnet_api.Migrations
{
  [DbContext(typeof(MyDbContext))]
  [Migration("20230224015607_addCompleteData")]
  partial class addCompleteData
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.3")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<DateTime?>("DateCompleted")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Description")
                      .HasColumnType("text");

            b.Property<bool>("IsComplete")
                      .HasColumnType("boolean");

            b.HasKey("Id");

            b.ToTable("TodoItems");
          });
#pragma warning restore 612, 618
    }
  }
}
